---
- hosts: localhost
  tags:
    - e2e
    - syncthing
    - unprivileged
  tasks:
    - include_role:
        name: create_namespace
      vars:
        num_namespaces: 3
        pss_enforce: restricted

    - include_role:
        name: gather_cluster_info

    # We're running everything as a normal user
    - name: Define podSecurityContext
      ansible.builtin.set_fact:
        podSecurityContext:
          fsGroup: 5678
          runAsGroup: 5678
          runAsNonRoot: true
          runAsUser: 1234
          seccompProfile:
            type: RuntimeDefault
      when: not cluster_info.is_openshift

    - include_role:
        name: test_syncthing_cluster_sync
      vars:
        num_syncthings: 3
        privileged: false
