---
- hosts: localhost
  tags:
    - e2e
    - syncthing
    - privileged
  tasks:
    - include_role:
        name: create_namespace
      vars:
        num_namespaces: 3

    - include_role:
        name: gather_cluster_info

    - include_role:
        name: test_syncthing_cluster_sync
      vars:
        num_syncthings: 3
        privileged: true
