---
# This tests the ansible roles that are used by the actual tests
- hosts: localhost
  tasks:
    - include_role:
        name: create_namespace
      vars:
        pss_enforce: restricted

    - include_role:
        name: gather_cluster_info

    - name: Define podSecurityContext
      ansible.builtin.set_fact:
        podSecurityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      when: not cluster_info.is_openshift

    - include_role:
        name: test_roles
